<script setup>
import { computed } from 'vue'
import { useUploadStore } from '../stores/uploadStore'
const upload=useUploadStore()
const faturamento=computed(()=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(upload.faturamentoMedio||0))
const segmentos=computed(()=>Object.entries(upload.segmentos||{}).sort((a,b)=>b[1]-a[1]).slice(0,5))
const maior=computed(()=>Math.max(...segmentos.value.map(([,v])=>v),1)), total=computed(()=>upload.totalClientes||1)
const cores=['#4e7cff','#2dd4bf','#9b7cff','#42d392','#f5a623']
</script>
<template><main class="page"><div class="shell"><header><h1>Visão Geral</h1><p>Customer intelligence at a glance.</p></header><section class="filters"><label>SEGMENTO<select><option>Todos os Segmentos</option></select></label><label>STATUS<select><option>Todos</option></select></label><label>NÍVEL<select><option>Todos</option></select></label><label>PERÍODO<select><option>Últimos 12 meses</option></select></label><button>Limpar filtros</button></section><section class="metrics"><article><span>TOTAL DE CLIENTES</span><strong>{{upload.totalClientes}}</strong><em>↑ dados da base atual</em></article><article><span>FATURAMENTO MÉDIO</span><strong>{{faturamento}}</strong><em>↑ por cliente</em></article><article><span>REGISTROS VÁLIDOS</span><strong>{{upload.registrosValidos}}</strong><i>— processados</i></article><article><span>CLIENTES ATIVOS</span><strong>{{upload.totalClientes-upload.registrosComErro}}</strong><b>{{upload.totalClientes?Math.round(((upload.totalClientes-upload.registrosComErro)/upload.totalClientes)*100):0}}% da base</b></article></section><section class="grid"><article class="panel"><h2>Distribuição por Segmento</h2><p>Participação de cada segmento na base total de clientes</p><div v-if="segmentos.length" class="bar"><i v-for="([,v],n) in segmentos" :key="n" :style="{width:`${v/total*100}%`,background:cores[n]}"></i></div><div v-if="segmentos.length" class="legend"><div v-for="([nome,v],n) in segmentos" :key="nome"><i :style="{background:cores[n]}"></i>{{nome}}<small>{{v}} clientes</small><b>{{Math.round(v/total*100)}}%</b></div></div><p v-else>Importe uma planilha para visualizar a distribuição.</p></article><article class="panel"><h2>Clientes por Nível</h2><p>Classificação por relevância comercial</p><div class="levels"><div v-for="([n,v,c]) in [['A',upload.clientesNivelA,'#42d392'],['B',upload.clientesNivelB,'#4e7cff'],['C',upload.clientesNivelC,'#f5a623']]" :key="n"><label :style="{color:c}">{{n}}</label><i><b :style="{width:`${v/total*100}%`,background:c}"></b></i><small>{{v}} clientes</small><strong>{{Math.round(v/total*100)}}%</strong></div></div></article></section><section class="panel return"><h2>Onde está o retorno?</h2><p>Faturamento por segmento — a resposta para a pergunta central do negócio</p><div v-for="([n,v],i) in segmentos" :key="n" class="row"><span>{{n}}</span><i><b :style="{width:`${v/maior*100}%`,background:cores[i]}"></b></i><strong>{{v}}</strong></div><div class="insight">O segmento de maior relevância apresenta uma oportunidade estratégica para expansão.</div></section></div></main></template>
<style scoped>
.page{min-height:calc(100vh - 64px);background:#080c15;color:#eef1fa;padding:38px 36px 70px}.shell{max-width:1450px;margin:auto}h1{font-size:38px;letter-spacing:-.05em;margin:0}header p,.panel>p{color:#929aae;margin:10px 0 28px}.filters,.metrics,.panel{border:1px solid #202737;background:#111624;border-radius:16px}.filters{display:flex;gap:10px;align-items:end;padding:14px;margin:28px 0 18px}.filters label,.metrics span{color:#667087;font:700 9px monospace;letter-spacing:.16em}.filters select{display:block;margin-top:6px;background:#191f2e;border:1px solid #293144;border-radius:8px;color:#e6e9f2;padding:9px;min-width:145px}.filters button{margin-left:auto;background:none;border:0;color:#a6adbc;text-transform:uppercase;font:700 10px monospace}.metrics{display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden}.metrics article{padding:27px 24px;border-right:1px solid #202737}.metrics article:last-child{border:0}.metrics strong{display:block;font-size:36px;letter-spacing:-.06em;margin:13px 0}.metrics em,.metrics b{font:12px monospace;color:#42d392}.metrics i{font:12px monospace;color:#667087}.grid{display:grid;grid-template-columns:1.25fr .9fr;gap:18px;margin-top:24px}.panel{padding:27px}.panel h2{font-size:18px;margin:0}.panel>p{font-size:13px;margin:6px 0 22px}.bar{height:13px;background:#1a2030;border-radius:99px;overflow:hidden;display:flex;margin-bottom:20px}.bar i{height:100%}.legend>div{display:flex;gap:11px;align-items:center;padding:8px 0;font-size:13px}.legend i{width:10px;height:10px;border-radius:3px}.legend small{color:#7d869a;margin-left:auto;font:11px monospace}.legend b{width:35px;text-align:right}.levels>div{display:grid;grid-template-columns:30px 1fr 90px 42px;gap:10px;align-items:center;margin:17px 0}.levels label{padding:7px 11px;background:#182b2d;border-radius:7px;font-weight:700}.levels>div>i,.row>i{display:block;height:9px;background:#1a2030;border-radius:99px;overflow:hidden}.levels b,.row b{display:block;height:100%;border-radius:99px}.levels small{color:#7d869a;font:11px monospace}.return{margin-top:18px}.row{display:grid;grid-template-columns:110px 1fr 75px;gap:10px;align-items:center;margin:15px 0;font-size:13px}.row strong{font:12px monospace;text-align:right}.insight{margin-top:24px;padding:14px;border:1px solid #314d93;background:#182644;border-radius:8px;color:#cbd3e7;font-size:13px}@media(max-width:760px){.page{padding:24px 16px}.filters,.metrics,.grid{display:block}.filters label{display:block;margin:10px}.metrics article{border-bottom:1px solid #202737}.grid .panel{margin-top:18px}.levels>div{grid-template-columns:30px 1fr 40px}.levels small{display:none}}
/* Acabamento visual alinhado à landing e ao login */
.page{background-color:#090d16;background-image:linear-gradient(rgba(255,255,255,.018) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:72px 72px}
.filters,.metrics,.panel{box-shadow:0 16px 38px rgba(0,0,0,.16)}
.metrics article,.panel{transition:border-color .25s ease,transform .25s ease,background .25s ease}
.metrics article:hover{background:#151d2d}
.panel:hover{border-color:#35415a;transform:translateY(-3px)}
.filters select{transition:border-color .2s ease,background .2s ease}
.filters select:hover,.filters select:focus{border-color:#536fce;background:#1d2638;outline:none}
.filters button{border:1px solid transparent;border-radius:7px;padding:9px 11px;transition:.2s}
.filters button:hover{border-color:#405070;background:#161e2d;color:#eaf0ff}
.insight{border-color:#35518d;background:#172442}
</style>
