<script setup>
import { computed } from 'vue'
import { useUploadStore } from '../stores/uploadStore'
const upload = useUploadStore()
const segmentos = computed(() => Object.entries(upload.segmentos || {}).sort((a,b) => b[1] - a[1]).slice(0,5))
const maior = computed(() => Math.max(...segmentos.value.map(([,v]) => v), 1))
const total = computed(() => upload.totalClientes || 1)
const cores = ['#5878e8','#31c7b2','#9877e8','#41c98a','#f0b34a']
const niveis = computed(() => [['Nível A', upload.clientesNivelA, '#31c7b2'], ['Nível B', upload.clientesNivelB, '#5878e8'], ['Nível C', upload.clientesNivelC, '#f0b34a']])
</script>
<template><main class="page"><div class="shell"><header class="title"><div><p>EVOLUÇÃO</p><h1>Indicadores da base</h1><span>Acompanhe a composição atual da sua carteira.</span></div><label>PERÍODO<select><option>Base atual</option></select></label></header><section class="chart-card"><div class="card-title"><div><h2>Evolução por segmento</h2><p>Representatividade de cada segmento na base processada</p></div><span class="legend-dot">Base de clientes</span></div><div v-if="segmentos.length" class="vertical"><article v-for="([nome,valor],i) in segmentos" :key="nome"><div><b>{{ valor }}</b><i :style="{height:`${Math.max(valor/maior*100,12)}%`,background:cores[i]}"></i></div><span>{{ nome }}</span></article></div><p v-else class="empty">Importe uma planilha para acompanhar a evolução da sua base.</p></section><section class="summary"><article><span>CLIENTES PROCESSADOS</span><b>{{ upload.totalClientes }}</b><em>base atual</em></article><article><span>REGISTROS VÁLIDOS</span><b>{{ upload.registrosValidos }}</b><em>dados prontos para análise</em></article><article><span>SEGMENTOS</span><b>{{ segmentos.length }}</b><em>categorias identificadas</em></article></section><section class="panel levels"><div><h2>Níveis de prioridade</h2><p>Classificação por relevância comercial</p></div><article v-for="([nome,valor,cor]) in niveis" :key="nome"><span>{{ nome }}</span><i><b :style="{width:`${valor/total*100}%`,background:cor}"></b></i><small>{{ valor }} clientes</small><strong>{{ Math.round(valor/total*100) }}%</strong></article></section></div></main></template>
<style scoped>
.page{min-height:calc(100vh - 64px);padding:38px 36px 70px;background:#090d16;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:72px 72px;color:#eef1fa}.shell{max-width:1450px;margin:auto}.title{display:flex;justify-content:space-between;align-items:end;margin-bottom:28px}.title p,.summary span{color:#78859a;font:10px ui-monospace,monospace;letter-spacing:.16em}.title h1{margin:9px 0;font-size:38px;letter-spacing:-.05em}.title span,.card-title p,.levels>div p{color:#929aae;font-size:14px}.title label{color:#929aae;font-size:11px}.title select{display:block;margin-top:7px;padding:10px 14px;border:1px solid #303a50;border-radius:8px;background:#151c2b;color:#eef1fa}.chart-card,.panel,.summary{border:1px solid #242e40;border-radius:16px;background:#111724;box-shadow:0 16px 38px #0003}.chart-card{padding:28px}.card-title{display:flex;justify-content:space-between}.card-title h2,.levels h2{margin:0;font-size:19px}.card-title p{margin:7px 0}.legend-dot{color:#9ba7b9;font:11px ui-monospace,monospace}.legend-dot:before{content:'';display:inline-block;width:8px;height:8px;margin-right:7px;border-radius:50%;background:#31c7b2}.vertical{display:flex;gap:20px;align-items:end;height:285px;padding:30px 10px 0;border-bottom:1px solid #263146}.vertical article{display:flex;flex:1;flex-direction:column;justify-content:end;height:100%;gap:10px;text-align:center}.vertical article>div{position:relative;display:flex;align-items:end;justify-content:center;height:100%}.vertical b{position:absolute;top:-23px;color:#c8d1df;font:11px ui-monospace,monospace}.vertical i{width:100%;max-width:100px;border-radius:6px 6px 0 0;transition:height .4s}.vertical span{color:#8793a7;font-size:12px}.empty{padding:80px 0;text-align:center;color:#8d98ab}.summary{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;margin:18px 0}.summary article{padding:26px;border-right:1px solid #242e40}.summary article:last-child{border:0}.summary b{display:block;margin:10px 0;font-size:32px}.summary em{color:#31c7b2;font-size:12px;font-style:normal}.levels{padding:28px}.levels>div{margin-bottom:25px}.levels>div p{margin-bottom:0}.levels article{display:grid;grid-template-columns:145px 1fr 110px 45px;gap:12px;align-items:center;margin:17px 0;font-size:13px}.levels i{display:block;height:10px;overflow:hidden;border-radius:99px;background:#1b2333}.levels i b{display:block;height:100%;border-radius:99px}.levels small{color:#7e8aa0;font:11px ui-monospace,monospace}.levels strong{text-align:right}@media(max-width:700px){.page{padding:25px 16px}.title{align-items:start;gap:20px}.title label{display:none}.summary{display:block}.summary article{border-bottom:1px solid #242e40}.levels article{grid-template-columns:100px 1fr 40px}.levels small{display:none}.vertical{gap:8px}.vertical span{font-size:10px}}
</style>
