<script setup>
import { computed } from 'vue'
import { useUploadStore } from '../stores/uploadStore'
const upload=useUploadStore()
const arquivo=computed(()=>upload.arquivo?.name||'Nenhuma planilha processada')
</script>
<template><main class="page"><div class="shell"><header><div><p>CONTROLE DE QUALIDADE</p><h1>Relatório de validação</h1><span>Arquivo: <b>{{arquivo}}</b></span></div><router-link to="/upload">Nova importação</router-link></header><template v-if="upload.temResultado"><section class="metrics"><article><span>TOTAL</span><b>{{upload.totalRegistros}}</b><small>linhas analisadas</small></article><article><span>VÁLIDOS</span><b>{{upload.registrosValidos}}</b><small>prontos para uso</small></article><article class="warn"><span>COM ERRO</span><b>{{upload.registrosComErro}}</b><small>requerem atenção</small></article><article><span>OCORRÊNCIAS</span><b>{{upload.totalErros}}</b><small>na validação</small></article></section><section class="content"><article class="panel"><p>RESUMO</p><h2>Erros por tipo</h2><div v-if="upload.errosPorTipo.length" class="error-types"><div v-for="item in upload.errosPorTipo" :key="item.tipo"><span>{{item.tipo}}</span><b>{{item.total}}</b></div></div><div v-else class="approved">✓ Nenhum erro encontrado. A base está pronta para análise.</div></article><article class="panel table"><div><p>DETALHAMENTO</p><h2>Ocorrências da planilha</h2></div><div v-if="upload.erros.length" class="scroll"><table><thead><tr><th>Linha</th><th>Campo</th><th>Tipo</th><th>Descrição</th></tr></thead><tbody><tr v-for="erro in upload.erros" :key="erro.id"><td>{{erro.linha}}</td><td>{{erro.campo}}</td><td>{{erro.tipo}}</td><td>{{erro.descricao}}</td></tr></tbody></table></div><div v-else class="approved">✓ A planilha foi aprovada sem pendências.</div></article></section></template><section v-else class="empty"><div>↗</div><h2>Ainda não há um relatório</h2><p>Importe uma planilha para iniciar a validação e visualizar os resultados.</p><router-link to="/upload">Ir para importação</router-link></section></div></main></template>
<style scoped>
.page{min-height:calc(100vh - 64px);padding:38px 36px 70px;background:#090d16;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:72px 72px;color:#eef1fa}.shell{max-width:1450px;margin:auto}header{display:flex;align-items:end;justify-content:space-between;margin-bottom:28px}header p,.metrics span,.panel>p{color:#78859a;font:10px ui-monospace,monospace;letter-spacing:.16em}h1{margin:9px 0;font-size:38px;letter-spacing:-.05em}header span{color:#929aae;font-size:14px}header span b{color:#cbd3df;font-weight:500}header>a,.empty>a{padding:11px 16px;border:1px solid #687fca;border-radius:8px;background:#415ba8;color:#fff;text-decoration:none;font-size:13px;font-weight:700;transition:.2s}header>a:hover,.empty>a:hover{background:#4c67b5}.metrics{display:grid;grid-template-columns:repeat(4,1fr);overflow:hidden;border:1px solid #242e40;border-radius:16px;background:#111724}.metrics article{padding:25px;border-right:1px solid #242e40}.metrics article:last-child{border:0}.metrics b{display:block;margin:12px 0;font-size:32px}.metrics small{color:#8995a9;font-size:12px}.metrics article:not(.warn) b{color:#dfe7f5}.metrics .warn b{color:#e993a0}.content{display:grid;grid-template-columns:.7fr 1.3fr;gap:18px;margin-top:18px}.panel,.empty{border:1px solid #242e40;border-radius:16px;background:#111724;box-shadow:0 16px 38px #0003}.panel{padding:27px}.panel h2{margin:8px 0 24px;font-size:18px}.error-types{border-block:1px solid #263146}.error-types div{display:flex;justify-content:space-between;padding:15px 0;border-bottom:1px solid #263146;font-size:13px}.error-types div:last-child{border:0}.error-types b{color:#e993a0}.approved{padding:15px;border:1px solid #285e58;border-radius:8px;background:#112622;color:#76dac9;font-size:13px}.table{overflow:hidden;padding:0}.table>div:first-child{padding:27px 27px 0}.scroll{overflow:auto}.table table{width:100%;min-width:620px;border-collapse:collapse;font-size:13px}.table th{padding:14px 20px;border-block:1px solid #263146;color:#7f8ba0;text-align:left;font:10px ui-monospace,monospace;letter-spacing:.12em}.table td{padding:15px 20px;border-bottom:1px solid #202a3b;color:#c4cedb}.table td:first-child{color:#aab9ee;font-weight:700}.empty{padding:78px 25px;text-align:center}.empty>div{display:grid;place-items:center;width:46px;height:46px;margin:auto;border:1px solid #415b9e;border-radius:50%;color:#9eafeb;font-size:21px}.empty h2{margin:19px 0 7px}.empty p{margin:0 auto 25px;max-width:400px;color:#929aae;line-height:1.6;font-size:14px}@media(max-width:700px){.page{padding:25px 16px}header{align-items:start;gap:16px}.metrics,.content{display:block}.metrics article{border-bottom:1px solid #242e40}.content .panel{margin-top:18px}.empty{padding:55px 22px}}
</style>
