<script setup>
import { computed, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useUploadStore } from '../stores/uploadStore'
const upload=useUploadStore(),router=useRouter(),arrastando=ref(false)
const nomeArquivo=computed(()=>upload.arquivo?.name||'Nenhum arquivo selecionado')
const tamanhoArquivo=computed(()=>upload.arquivo?`${(upload.arquivo.size/1024).toFixed(1)} KB`:'')
function selecionar(file){if(file)upload.selecionarArquivo(file)}
function soltar(event){arrastando.value=false;selecionar(event.dataTransfer.files[0])}
async function processar(){await upload.processarPlanilha();if(upload.temResultado)router.push('/relatorios')}
</script>
<template><main class="page"><div class="shell"><header><p>ENTRADA DE DADOS</p><h1>Importar uma base</h1><span>Envie uma planilha para organizar sua carteira e iniciar a análise.</span></header><section class="upload-card"><div :class="['dropzone',arrastando?'dragging':'']" @dragover.prevent="arrastando=true" @dragleave.prevent="arrastando=false" @drop.prevent="soltar"><div class="upload-icon">↑</div><h2>Selecione sua planilha</h2><p>Arraste o arquivo aqui ou escolha no seu computador.<br>Aceitamos XLSX, XLS e CSV.</p><label>Escolher arquivo<input type="file" accept=".xlsx,.xls,.csv" @change="selecionar($event.target.files[0])"></label></div><div v-if="upload.arquivo" class="selected"><div><span>ARQUIVO SELECIONADO</span><b>{{nomeArquivo}}</b><small>{{tamanhoArquivo}} · pronto para validação</small></div><button :disabled="upload.carregando" @click="processar">{{upload.carregando?'Lendo arquivo...':'Processar e gerar relatório'}}</button></div><div v-if="upload.erros.length&&!upload.temResultado" class="errors"><p v-for="erro in upload.erros" :key="erro.id">{{erro.descricao}}</p></div></section></div></main></template>
<style scoped>
.page{min-height:calc(100vh - 64px);padding:38px 36px 70px;background:#090d16;background-image:linear-gradient(#ffffff08 1px,transparent 1px),linear-gradient(90deg,#ffffff08 1px,transparent 1px);background-size:72px 72px;color:#eef1fa}.shell{max-width:1120px;margin:auto}header{margin-bottom:30px}header p,.selected span{color:#78859a;font:10px ui-monospace,monospace;letter-spacing:.16em}h1{margin:9px 0;font-size:38px;letter-spacing:-.05em}header span{color:#929aae;font-size:14px}.upload-card,.steps{border:1px solid #242e40;border-radius:16px;background:#111724;box-shadow:0 16px 38px #0003}.upload-card{padding:22px}.dropzone{display:flex;min-height:330px;flex-direction:column;align-items:center;justify-content:center;border:1px dashed #43516b;border-radius:11px;background:#0d121d;text-align:center;transition:.25s}.dropzone:hover,.dragging{border-color:#5878e8;background:#121a2b}.upload-icon{display:grid;place-items:center;width:45px;height:45px;border:1px solid #5878e8;border-radius:50%;color:#aab9ee;font-size:22px}.dropzone h2{margin:18px 0 5px;font-size:18px}.dropzone p{color:#929aae;font-size:14px;line-height:1.6}.dropzone label,.selected button{margin-top:18px;padding:11px 16px;border:1px solid #687fca;border-radius:8px;background:#415ba8;color:#fff;font-size:13px;font-weight:700;cursor:pointer;transition:.2s}.dropzone label:hover,.selected button:hover{background:#4c67b5;transform:translateY(-2px)}.dropzone input{display:none}.selected{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-top:15px;padding:17px;border:1px solid #32466e;border-radius:9px;background:#101a2b}.selected b,.selected small{display:block;margin-top:6px}.selected small{color:#8f9bb0;font-size:12px}.selected button{margin:0;border:0}.selected button:disabled{opacity:.6}.errors{margin-top:14px;padding:13px;border-left:2px solid #e47787;background:#2a131b;color:#f2c6cc;font-size:13px}.errors p{margin:4px}.steps{display:grid;grid-template-columns:repeat(3,1fr);overflow:hidden;margin-top:18px}.steps article{padding:25px;border-right:1px solid #242e40}.steps article:last-child{border:0}.steps b{color:#7189db;font:12px ui-monospace,monospace}.steps h3{margin:29px 0 8px;font-size:16px}.steps p{margin:0;color:#929aae;font-size:13px;line-height:1.55}@media(max-width:700px){.page{padding:25px 16px}.selected,.steps{display:block}.selected button{width:100%;margin-top:14px}.steps article{border-bottom:1px solid #242e40}.dropzone{min-height:285px}}
</style>
